// original from https://pastebin.com/7EDHLdsi

export const levelNamesByFilenames = {
  newtutorial1: "Beginner Tutorial",
  newtutorial2: "Combat Tutorial",
  newtutorial3: "Advanced Tutorial",
  downhill: "Downhill",
  shadedgrove: "Shaded Grove",
  dahlia: "Dahlia",
  fields: "Fields",
  momentum: "Valley",
  fireflyforest: "Firefly Forest",
  tunnels: "Tunnels",
  momentum2: "Dusk Run",
  suntemple: "Overgrown Temple",
  ascent: "Ascent",
  summit: "Summit",
  grasscave: "Grass Cave",
  den: "Wild Den",
  autumnforest: "Ruins",
  garden: "Ancient Garden",
  hyperdifficult: "Night Temple",
  atrium: "Atrium",
  secretpassage: "Secret Passage",
  alcoves: "Alcoves",
  mezzanine: "Mezzanine",
  cave: "Caverns",
  cliffsidecaves: "Cliffside Caves",
  library: "Library",
  courtyard: "Courtyard",
  precarious: "Archive",
  treasureroom: "Knight Hall",
  arena: "Store Room",
  ramparts: "Ramparts",
  moontemple: "Moon Temple",
  observatory: "Observatory",
  parapets: "Ghost Parapets",
  brimstone: "Tower",
  vacantlot: "Vacant Lot",
  sprawl: "Landfill",
  development: "Development",
  abandoned: "Abandoned Carpark",
  park: "Park",
  boxes: "Construction Site",
  chemworld: "Apartments",
  factory: "Warehouse",
  tunnel: "Forgotten Tunnel",
  basement: "Basement",
  scaffold: "Scaffolding",
  cityrun: "Rooftops",
  clocktower: "Clocktower",
  concretetemple: "Concrete Temple",
  alley: "Alleyway",
  hideout: "Hideout",
  control: "Control",
  ferrofluid: "Ferrofluid",
  titan: "Titan",
  satellite: "Satellite Debris",
  vat: "Vats",
  venom: "Server Room",
  security: "Security",
  mary: "Research",
  wiringfixed: "Wiring",
  containment: "Containment",
  orb: "Power Room",
  pod: "Access",
  mary2: "Backup Shift",
  coretemple: "Core Temple",
  abyss: "Abyss",
  dome: "Dome",
  kilodifficult: "Kilo Difficult",
  megadifficult: "Mega Difficult",
  gigadifficult: "Giga Difficult",
  teradifficult: "Tera Difficult",
  petadifficult: "Peta Difficult",
  exadifficult: "Exa Difficult",
  zettadifficult: "Zetta Difficult",
  yottadifficult: "Yotta Difficult",
};

module.exports = { levelNamesByFilenames };
