const voices = [
  { speaker: "Agnes", locale: "en_US" },
  { speaker: "Albert", locale: "legacy" },
  { speaker: "Alex", locale: "en_US" },
  { speaker: "Alice", locale: "it_IT" },
  { speaker: "Alva", locale: "sv_SE" },
  { speaker: "Amelie", locale: "fr_CA" },
  { speaker: "Anna", locale: "de_DE" },
  { speaker: "Bad_News", locale: "legacy" },
  { speaker: "Bahh", locale: "legacy" },
  { speaker: "Bells", locale: "legacy" },
  { speaker: "Boing", locale: "legacy" },
  { speaker: "Bruce", locale: "en_US" },
  { speaker: "Bubbles", locale: "legacy" },
  { speaker: "Carmit", locale: "he_IL" },
  { speaker: "Cellos", locale: "legacy" },
  { speaker: "Claire", locale: "nl_NL" },
  { speaker: "Damayanti", locale: "id_ID" },
  { speaker: "Daniel", locale: "en_GB" },
  { speaker: "Deranged", locale: "legacy" },
  { speaker: "Diego", locale: "es_AR" },
  { speaker: "Ellen", locale: "nl_BE" },
  { speaker: "Felipe", locale: "pt_BR" },
  { speaker: "Fiona", locale: "en-scotland" },
  { speaker: "Fred", locale: "en_US" },
  { speaker: "Good_News", locale: "legacy" },
  { speaker: "Hysterical", locale: "legacy" },
  { speaker: "Ioana", locale: "ro_RO" },
  { speaker: "Joana", locale: "pt_PT" },
  { speaker: "Jorge", locale: "es_ES" },
  { speaker: "Juan", locale: "es_MX" },
  { speaker: "Junior", locale: "en_US" },
  { speaker: "Kanya", locale: "th_TH" },
  { speaker: "Karen", locale: "en_AU" },
  { speaker: "Kate", locale: "en_GB" },
  { speaker: "Kathy", locale: "en_US" },
  { speaker: "Kyoko", locale: "ja_JP" },
  { speaker: "Laura", locale: "sk_SK" },
  { speaker: "Lee", locale: "en_AU" },
  { speaker: "Lekha", locale: "hi_IN" },
  { speaker: "Luca", locale: "it_IT" },
  { speaker: "Luciana", locale: "pt_BR" },
  { speaker: "Maged", locale: "ar_SA" },
  { speaker: "Mariska", locale: "hu_HU" },
  { speaker: "Markus", locale: "de_DE" },
  { speaker: "Mei-Jia", locale: "zh_TW" },
  { speaker: "Melina", locale: "el_GR" },
  { speaker: "Milena", locale: "ru_RU" },
  { speaker: "Moira", locale: "en_IE" },
  { speaker: "Monica", locale: "es_ES" },
  { speaker: "Nora", locale: "nb_NO" },
  { speaker: "Oliver", locale: "en_GB" },
  { speaker: "Paulina", locale: "es_MX" },
  { speaker: "Princess", locale: "en_US" },
  { speaker: "Ralph", locale: "en_US" },
  { speaker: "Rishi", locale: "en_IN" },
  { speaker: "Samantha", locale: "en_US" },
  { speaker: "Sara", locale: "da_DK" },
  { speaker: "Satu", locale: "fi_FI" },
  { speaker: "Serena", locale: "en_GB" },
  { speaker: "Sin-ji", locale: "zh_HK" },
  { speaker: "Tessa", locale: "en_ZA" },
  { speaker: "Thomas", locale: "fr_FR" },
  { speaker: "Ting-Ting", locale: "zh_CN" },
  { speaker: "Trinoids", locale: "legacy" },
  { speaker: "Veena", locale: "en_IN" },
  { speaker: "Vicki", locale: "en_US" },
  { speaker: "Victoria", locale: "en_US" },
  { speaker: "Whisper", locale: "legacy" },
  { speaker: "Xander", locale: "nl_NL" },
  { speaker: "Yelda", locale: "tr_TR" },
  { speaker: "Yuna", locale: "ko_KR" },
  { speaker: "Yuri", locale: "ru_RU" },
  { speaker: "Zarvox", locale: "legacy" },
  { speaker: "Zosia", locale: "pl_PL" },
  { speaker: "Zuzana", locale: "cs_CZ" },
];

const rates = [
  0.25,
  0.5,
  1,
  1.5,
  2
];

module.exports = { voices, rates };
